const imageBasePath = "../../assets/images";

export default {
  SPLASH: {
    APP_LOGO_GRAY: require(`${imageBasePath}/Music_Card_LogoGray.png`),
    CONGRATES: require(`${imageBasePath}/congrates.gif`),
    DONE: require(`${imageBasePath}/done.gif`),
  },
  HOME: {
    NOTIFICATION: require(`${imageBasePath}/notification.png`),
    LOCATION: require(`${imageBasePath}/location.png`),
    SEARCH: require(`${imageBasePath}/search.png`),
    VIDEO_OF_DAY: require(`${imageBasePath}/videoOfDay.png`),
    SEE_MORE: require(`${imageBasePath}/seemore.png`),
    VIDEO: require(`${imageBasePath}/editors_1.png`),
    VIDEO1: require(`${imageBasePath}/video1.png`),
    VIDEO2: require(`${imageBasePath}/editors_3.png`),
    VIDEO3: require(`${imageBasePath}/video3.png`),
    STAR: require(`${imageBasePath}/star.png`),
    LOGOUT: require(`${imageBasePath}/logout.png`),
    MONTH: require(`${imageBasePath}/annual.png`),
    IMAGE_PLACEHOLDER: require(`${imageBasePath}/imagePlaceholder.png`),
  },
  EDITOR_PICK: {
    BACK: require(`${imageBasePath}/back.png`),
  },
  LOG_IN: {
    CLOSE: require(`${imageBasePath}/close.png`),
    GOOGLE: require(`${imageBasePath}/google_login.png`),
  },
  COMPLETE_PROFILE: {
    UPLOAD: require(`${imageBasePath}/upload_image.png`),
  },
  MY_PROFILE: {
    SETTING: require(`${imageBasePath}/settings.png`),
    USER: require(`${imageBasePath}/editors_1.png`),
    RESTUSER: require(`${imageBasePath}/restuser.png`),
    EDIT: require(`${imageBasePath}/edit.png`),
  },
  UPLOAD_VIDEO: {
    UPLOAD: require(`${imageBasePath}/upload.png`),
    CAMERA: require(`${imageBasePath}/video-camera.png`),
    LINK: require(`${imageBasePath}/link.png`),
    COVER_ICON: require(`${imageBasePath}/cover_placeholder.png`),
    VIDEO_VIEW: require(`${imageBasePath}/videoView.png`),
  },
  APP: {
    UPLOAD_ICON: require(`${imageBasePath}/uploadIcon.png`),
    PROFILE: require(`${imageBasePath}/profile.png`),
    HOME: require(`${imageBasePath}/home.png`),
    PLAYLIST: require(`${imageBasePath}/playlist.png`),
    FOLLOWING: require(`${imageBasePath}/following.png`),
    FAVIOURTE: require(`${imageBasePath}/favorites.png`),
    ADD_PLAYLIST: require(`${imageBasePath}/addPlaylist.png`),
    DELETE: require(`${imageBasePath}/delete.png`),
    LIKE: require(`${imageBasePath}/like.png`),
    LIKED: require(`${imageBasePath}/liked.png`),
    THUMBS: require(`${imageBasePath}/thumbs.png`),
    THUMBSUP: require(`${imageBasePath}/thumbsUp.png`),
    CLAPPS: require(`${imageBasePath}/clapp.png`),
    CLAPPED: require(`${imageBasePath}/clapped.png`),
    REMOVE: require(`${imageBasePath}/remove.png`),
    USER: require(`${imageBasePath}/user.png`),
    UPLOAD_NEW: require(`${imageBasePath}/uploadNew.png`),
    REQUEST: require(`${imageBasePath}/requests.png`),
    TIPS: require(`${imageBasePath}/tips.png`),
    SHARE: require(`${imageBasePath}/share.png`),
    FLAG: require(`${imageBasePath}/flag.png`),
    SILVER: require(`${imageBasePath}/silver.png`),
    BURN: require(`${imageBasePath}/burn.png`),
    GOLD: require(`${imageBasePath}/gold.png`),
    RATING: require(`${imageBasePath}/star.png`),
  },
};
