const APP_STRING = {
  EMPTY: "",
  HOME: "Home",
  TIP_SAVED: "Thankyou for your support.",
  WELCOME: "Welcome",
  SPLASH: "Splash",
  MUSIC_CARD: "Music Card",
  WELCOME: "Welcome to",
  LETS_GO: "Let's go",
  USER_PROFILE_INFORMATION: "USER_PROFILE_INFORMATION",
  CONNECT_EMAIL: "Connect with Email",
  LOGIN_USERNAME: "Log in with username",
  NEXT: "Next",
  DONE: "Done",
  FOLLOW: "Follow",
  YES: "Yes",
  NO: "No",
  VIDEO_TYPE: ".mp4",
  VERIFY: "Verify",
  REGISTER: "Register",
  SUBMIT: "Submit",
  UPLOAD: "Upload",
  USER_TOKEN: "USER_TOKEN",
  USER_INFORMATION: "USER_INFO",
  LOGIN: "Login",
  SONG_HAS_REMOVED_IN_PLAYLIST:
    "Song has been removed from playlist successfully.",
  SONG_HAS_ADDED_IN_PLAYLIST: "Song has been added in playlist successfully.",
  SONG_HAS_ADDED_IN_FAV: "Song has been added in favourite successfully.",
  SONG_HAS_LIKED: "Song has been Liked  successfully.",
  SONG_HAS_CLAPPED: "Song has been Clapped  successfully.",
  SONG_HAS_DISLIKE: "Song has been Removed from like  successfully.",
  PLAYLIST_DELETED_SUCCESSFULLY: "Playlist has been deleted successfully",
  PLAYLIST_RENAMED_SUCCESSFULLY: "Playlist has been renamed successfully",
  SAVE: "Save",
  RATING_SAVED: "Thanks for Rating.",
  FORGOT_PASSWORD: "Forgot Password",
  REGISTER_USER: "Register here",
  SUCCESS: "Success",
  ENTER_EMAIL: "Please enter email.",
  ENTER_PASSWORD: "Please enter password.",
  ENTER_ABOUT: "Please enter about yourself.",
  ENTER_CO_NUM: "Please enter contact number.",
  ENTER_VALID_CO_NUM: "Please enter valid contact number.",
  ENTER_VALID_EMAIL: "Please enter valid email.",
  ENTER_SIX_DIGIT_PASSWORD: "Please enter atleast six character  password",
  ENTER_F_NAME: "Please enter first name.",
  ENTER_L_NAME: "Please enter last name.",
  ENTER_USERNAME: "Please enter username.",
  ENTER_CONFIRM_PASSWORD: "Please enter confirm password.",
  BOTHPASS_DOES_NOT_MATCH: "Both password does't match.",
  INCORRECT_DETAILS: "User email/password incorrect.",
  USER_ALREADY_EXISTS: "User already exist, please try with another email.",
  REGISTRATION_SUCCESS: "Registration Successfull.",
  SUCCESSFULL_REQUEST: "Request Successfully created.",
  REQUEST_CANCEL: "Request Cancel.",
  ENTER_PLAYLIST_NAME: "Please enter Playlist name",
  EMAIL_NOT_FOUND: "User Not Found.",
  OOPS: "oops something went wrong please try after some time.",
  PROFILE_PIC_UPDATED: "Profile picture has been uploaded Successfully",
  SONG_HAS_UPLOADED: "Your song has been successfully uploaded.",
  LOCATION_UPDATED: "Your Location has been successfully Updated.",
  USER_INFORMATION_UPDATED: "Your Information has been uploaded Successfully",
  PLAYLIST_CREATED_SUCCESSFULLY: "Playlist Successfully created",
  CANT_HAVE_SAME_NAME_PLAYLIST: "You can't create same name playlist",
  ENTER_DESC: "Please enter description",
  REQUEST_GENERATED_SUCCESS: "Request has been sent successfully.",
  REPORT: "Report has been saved successfully.",
  CITY_ERROR: "Please select city.",
  REPORT_NON_EMPTY: "Please enter report reason and description.",
  OTP_GENERATION_FAIL: "OTP generation fail",
  OTP_VALIDATION_FAIL: "OTP validation fail",
  GENERATE_OTP_LABEL: "Send OTP",
  VALIDATE_OTP_LABEL: "Validate OTP",
};
export default APP_STRING;
