// Login Actions:
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

//Register Actions:
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

//Logout Actions:
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
//Forgot password Actions:
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
//UserLoggedIn Actions:
export const LOGGED_IN_USER_REQUEST = "LOGGED_IN_USER_REQUEST";
export const LOGGED_IN_USER_SUCCESS = "LOGGED_IN_USER_SUCCESS";
export const LOGGED_IN_USER_FAILURE = "LOGGED_IN_USER_FAILURE";
//Upload profile pic Actions:
export const UPLOAD_PROFILE_PIC_REQUEST = "UPLOAD_PROFILE_PIC_REQUEST";
export const UPLOAD_PROFILE_PIC_SUCCESS = "UPLOAD_PROFILE_PIC_SUCCESS";
export const UPLOAD_PROFILE_PIC_FAILURE = "UPLOAD_PROFILE_PIC_FAILURE";

export const LOGGED_IN_USER_INFORMATION = "LOGGED_IN_USER_INFORMATION";